### PR TITLE
VLC patches to allow compilation with the medialibrary master branch

### LINKED ISSUE #1583: VLC error
I got this error by building VLC today. I have two PC´s. One PC shows me the following error. The other produced a green screen and an restart of the PC.

10:22:40 ┌ vlc git  ..................................... [Updates found]
10:22:40 ├ Running uninstall...
10:22:42 ├ Running autoreconf...
10:23:54 ├ Running configure...
10:30:15 ├ Running install...
Likely error (tail of the failed operation logfile):
      |                  ^~~~~~~~~~~~~~~~~~
make[4]: *** [Makefile:27524: misc/medialibrary/libmedialibrary_plugin_la-medialib.lo] Error 1
make[4]: Leaving directory '/build/vlc-git/build-64bit/modules'
make[3]: *** [Makefile:31837: install-recursive] Error 1
make[3]: Leaving directory '/build/vlc-git/build-64bit/modules'
make[2]: *** [Makefile:32268: install] Error 2
make[2]: Leaving directory '/build/vlc-git/build-64bit/modules'
make[1]: *** [Makefile:1573: install-recursive] Error 1
make[1]: Leaving directory '/build/vlc-git/build-64bit'
make: *** [Makefile:2042: install] Error 2
install failed. Check C:/media-autobuild_suite-master/build/vlc-git/build-64bit/ab-suite.install.log
This is required for other packages, so this script will exit.
10:43:00   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/iAlQ.zip

### PR DESCRIPTION
**Pull request by moisespr123**
Added the following 2 patches:

* [vlc-corrected-patch](https://gist.github.com/moisespr123/2369978dc603ed1e67bdf7aba7304416): This is a rebase of the original patch by @1480c1 to make it apply to VLC's master branch.
* [medialib-patch](https://gist.github.com/moisespr123/70e16f70f5d016c3d0f0dacbf97526f0): This allows us to compile VLC using medialibrary master branch.

Note that VLC is still buggy. It will work, but will present an exception upon launching it. Press ignore and it will work. It has issues playing back videos (some doesn't open the video window. Other have distorted colors), but I'm sure this is not related to the above patches and is something else with the codecs.

Fixes #1583

### CODE REVIEW

File: build/media-suite_compile.sh [hunk 1]
```diff
@@ -2590,7 +2590,8 @@ if [[ $vlc == y ]]; then
         # msys2's patches
         # Issues due to conflicting `vlc_module_name` between libvlc and libvlccore when linking vlc-static.exe and undefines.
         # having gpg-error after GCRYPT_LIBS causes some issues, and since it's already included in GCRYPT_LIBS
-        do_patch "https://gist.githubusercontent.com/1480c1/8c50a0867aa1afceac064d2162120dde/raw/vlc-mabs.patch" am
+        do_patch "https://gist.githubusercontent.com/moisespr123/2369978dc603ed1e67bdf7aba7304416/raw/f83d6cd9171765ee87140bfc1555529aa029f240/vlc-corrected-patch" am
+        do_patch "https://gist.githubusercontent.com/moisespr123/70e16f70f5d016c3d0f0dacbf97526f0/raw/ad70ecd5db0b6349cb47c85932ce5e408cbb7004/medialib-patch"
```
Comment (1480c1) [inline build/media-suite_compile.sh:2594]:
```suggestion
        do_patch "https://gist.githubusercontent.com/moisespr123/2369978dc603ed1e67bdf7aba7304416/raw/vlc-corrected-patch" am
        do_patch "https://gist.githubusercontent.com/moisespr123/70e16f70f5d016c3d0f0dacbf97526f0/raw/medialib-patch"
```

remove the hash of the patches, this allows you to update them without updating the link

Comment (moisespr123) [reply build/media-suite_compile.sh]: Removed the hashes.

**Comment by j-mas** [comment]
Now I get this output! What should I do?

02:01:26 ┌ vlc git  .................................. [Recently updated]
02:01:29 ├ Running autoreconf...
Package libcddb was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcddb.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcddb' found
02:02:52 ├ Running configure...
02:09:46 ├ Running install...
Likely error (tail of the failed operation logfile):
collect2.exe: error: ld returned 1 exit status
make[4]: *** [Makefile:15623: libavcodec_plugin.la] Error 1
make[4]: Leaving directory '/build/vlc-git/build-64bit/modules'
make[3]: *** [Makefile:32189: install-recursive] Error 1
make[3]: Leaving directory '/build/vlc-git/build-64bit/modules'
make[2]: *** [Makefile:32627: install] Error 2
make[2]: Leaving directory '/build/vlc-git/build-64bit/modules'
make[1]: *** [Makefile:1574: install-recursive] Error 1
make[1]: Leaving directory '/build/vlc-git/build-64bit'
make: *** [Makefile:2043: install] Error 2
install failed.

**Comment by 1480c1** [comment]
If you open mintty and run `pacman -Ss libcddb` what does it output?

**Comment by j-mas** [comment]
That is the output:

inuya@DESKTOP-3D73IMN /trunk
$ pacman -Ss libcddb
mingw32/mingw-w64-i686-libcddb 1.3.2-5
    Library that implements the different protocols (CDDBP, HTTP, SMTP) to access data on a CDDB server (e.g.
    http://freedb.org) (mingw-w64)
mingw64/mingw-w64-x86_64-libcddb 1.3.2-5
    Library that implements the different protocols (CDDBP, HTTP, SMTP) to access data on a CDDB server (e.g.
    http://freedb.org) (mingw-w64)
inuya@DESKTOP-3D73IMN /trunk
$

**Comment by 1480c1** [comment]
Try again with latest

**Comment by j-mas** [comment]
I did. Now I get the following error message:

19:20:22 ┌ vlc git  ..................................... [Updates found]
 ├ Running autoreconf...
19:21:56 ├ Running configure...
19:30:12 ├ Running install...
Likely error (tail of the failed operation logfile):
collect2.exe: error: ld returned 1 exit status
make[4]: *** [Makefile:20125: libskins2_plugin.la] Error 1
make[4]: Leaving directory '/build/vlc-git/build-64bit/modules'
make[3]: *** [Makefile:32175: install-recursive] Error 1
make[3]: Leaving directory '/build/vlc-git/build-64bit/modules'
make[2]: *** [Makefile:32613: install] Error 2
make[2]: Leaving directory '/build/vlc-git/build-64bit/modules'
make[1]: *** [Makefile:1575: install-recursive] Error 1
make[1]: Leaving directory '/build/vlc-git/build-64bit'
make: *** [Makefile:2044: install] Error 2
install failed.

**Comment by 1480c1** [comment]
Need the log

**Comment by j-mas** [comment]
Where can I find the log?

**Comment by 1480c1** [comment]
log.zip

**Comment by j-mas** [comment]
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4568625/logs.zip)

**Comment by 1480c1** [comment]
```c
  CXXLD    libskins2_plugin.la
C:/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/media-autobuild_suite-master/msys64/mingw64/lib/libharfbuzz.a(libharfbuzz_la-hb-ft.o):(.text+0xbd0): undefined reference to `FT_Get_MM_Var'
C:/media-autobuild_suite-master/msys64/mingw64/lib/libharfbuzz.a(libharfbuzz_la-hb-ft.o):(.text+0xbd0): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `FT_Get_MM_Var'
C:/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/media-autobuild_suite-master/msys64/mingw64/lib/libharfbuzz.a(libharfbuzz_la-hb-ft.o):(.text+0xc2f): undefined reference to `FT_Get_Var_Blend_Coordinates'
C:/media-autobuild_suite-master/msys64/mingw64/lib/libharfbuzz.a(libharfbuzz_la-hb-ft.o):(.text+0xc2f): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `FT_Get_Var_Blend_Coordinates'
C:/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/media-autobuild_suite-master/msys64/mingw64/lib/libharfbuzz.a(libharfbuzz_la-hb-ft.o):(.text+0xca2): undefined reference to `FT_Done_MM_Var'
C:/media-autobuild_suite-master/msys64/mingw64/lib/libharfbuzz.a(libharfbuzz_la-hb-ft.o):(.text+0xca2): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `FT_Done_MM_Var'
C:/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/media-autobuild_suite-master/msys64/mingw64/lib/libharfbuzz.a(libharfbuzz_la-hb-ft.o):(.text+0x11f6): undefined reference to `FT_Set_Var_Blend_Coordinates'
C:/media-autobuild_suite-master/msys64/mingw64/lib/libharfbuzz.a(libharfbuzz_la-hb-ft.o):(.text+0x11f6): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `FT_Set_Var_Blend_Coordinates'
```
that is the main information I needed

**Comment by 1480c1** [comment]
Seems like somethings missing and it's not adding freetype to link it with

**Comment by j-mas** [comment]
I compiled it completly new. Now it works! Thank you very much for your patience! 👍
