### PR TITLE
do_rust: Unset RUSTC_WRAPPER if command -v sccache fails

### LINKED ISSUE #1399: failed sccache build
┌ sccache git  ........................................ [Recently updated]
├ Running rust.update...
├ Running rust.build...
Likely error (tail of the failed operation logfile):
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.
error: failed to run `rustc` to learn about target-specific information

Caused by:
  could not execute process `sccache rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro` (never executed)

Caused by:
  Det går inte att hitta filen. (os error 2)
rust.build failed. Check D:/media-ab_suite/build/sccache-git/ab-suite.rust.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/ztt8.zip
Copy and paste [logs.zip](https://0x0.st/ztt8.zip) in the GitHub issue.

### PR DESCRIPTION
**Pull request by 1480c1**
Should Fix #1399 and #1403

### CODE REVIEW

File: build/media-suite_compile.sh [hunk 1]
```diff
@@ -173,8 +173,8 @@ if [[ $ripgrep = y || $rav1e = y || $dssim = y ]]; then
 
     _check=(bin/sccache.exe)
     if do_vcs "https://github.com/mozilla/sccache.git"; then
-        do_uninstall "${_check[@]}"
         do_rust
+        sccache --stop-server >/dev/null 2>&1 || false
```
Comment (wiiaboo) [inline build/media-suite_compile.sh]: Shouldn't we check if sccache exists first?

Comment (1480c1) [reply build/media-suite_compile.sh]:
```suggestion
        sccache --stop-server >/dev/null 2>&1 || true
```

That's what the to dev nulll and 2>&1 are for, just ignore if it fails

But I did make the mistake of putting false there
